/* eslint-disable no-undef */

// Data
const PROJECTS = [
  {
    title: "kaveo — AI-Native Cloud Security Platform",
    subtitle: "Co-Founder, Zhask · Flagship product · Shipping",
    classification: "FLAGSHIP",
    status: "BUILDING",
    stampColor: "accent",
    objective: "Build the cloud security platform AI can't hallucinate: deterministic ground truth from read-only AWS APIs, an immutable evidence ledger, and a grounded-AI layer where every claim must cite proof — or it is never stored.",
    outcome: "Self-hosted, zero-egress CSPM/CNAPP with 96 deterministic detectors and 43 AWS collectors. Zero AI agents touch the detection path; the AI layer only prioritizes, explains, and remediates — always cited to stored evidence. Native MCP server exposes read-only, cited findings to the customer's own agents.",
    steps: [
      "Designed the collector layer — 43 collectors pulling IAM, network, data and workload config straight from read-only AWS APIs",
      "Wrote 96 deterministic detectors against resources and the IAM/reachability graph — plain, auditable code, no agents",
      "Built the immutable observation ledger so every finding ships with its receipts",
      "Enforced grounded AI in the data model: each claim is a (text, citation) pair; uncited or misciting claims are dropped before storage",
      "Closed the loop — prioritize by real reachability and blast radius, draft and apply the fix via a scoped write role, re-scan to prove the finding no longer fires",
      "Added continuous drift/regression watch and a native MCP server for agent-native, read-only access",
    ],
    stack: ["AWS", "IAM Graph Analysis", "Deterministic Detection", "Grounded AI / RAG", "MCP", "Self-Hosted", "Python", "Zero-Egress"],
    metrics: [
      { value: "96", label: "DETECTORS" },
      { value: "43", label: "AWS COLLECTORS" },
      { value: "0", label: "AI AGENTS IN DETECTION" },
      { value: "300+", label: "AUTOMATED TESTS" },
    ],
  },
  {
    title: "Penetration Testing & Threat Intelligence Capstone",
    subtitle: "Team Lead · IIIT Bangalore · Capstone",
    classification: "TLP:AMBER",
    status: "DECLASSIFIED",
    stampColor: "amber",
    objective: "Lead a red-team engagement against simulated enterprise apps; map findings to MITRE ATT&CK and produce executive-grade risk reports.",
    outcome: "Delivered a 40-page threat intel report identifying 12 critical, 18 high vulns. Remediation playbook adopted by the program for subsequent cohorts.",
    steps: [
      "Scoped engagement boundaries with stakeholders; defined ROE",
      "Recon with Nmap + custom enumeration scripts",
      "Exploited OWASP Top-10 surface via Burp Suite",
      "Mapped TTPs to MITRE ATT&CK matrix (T1190, T1059, T1078)",
      "Authored remediation roadmap prioritized by CVSS + business impact",
    ],
    stack: ["MITRE ATT&CK", "Burp Suite", "Nmap", "Metasploit", "Kali", "OWASP Top 10"],
    metrics: [
      { value: "12", label: "CRIT FINDINGS" },
      { value: "40pp", label: "REPORT" },
      { value: "T1", label: "TEAM LEAD" },
    ],
  },
  {
    title: "Zero Trust Electronic Voting System (ZTEV)",
    subtitle: "Research grant · Advanced Cyber Cert · IIIT-B",
    classification: "TLP:RED",
    status: "OPERATIONAL",
    stampColor: "accent",
    objective: "Mitigate BYOD voting risks with a Zero Trust architecture: continuous verification, blockchain-backed audit, and AES-256 ballot envelopes.",
    outcome: "Working prototype with MFA, immutable audit log, and Snort-monitored ZTNA. Secured a research grant for continued development.",
    steps: [
      "Threat-modeled BYOD voting against STRIDE",
      "Designed ZTNA policy graph; implemented per-request reauthentication",
      "Layered AES-256 envelope encryption over ballot payloads",
      "Wired blockchain audit log for tamper evidence",
      "Tuned Snort IDS rules for ZTNA traffic anomalies",
    ],
    stack: ["Zero Trust", "Blockchain", "AES-256", "Snort IDS", "MFA", "ZTNA"],
    metrics: [
      { value: "AES-256", label: "ENVELOPE" },
      { value: "MFA", label: "ENFORCED" },
      { value: "GRANT", label: "AWARDED" },
    ],
  },
  {
    title: "PMRSS — Privacy-Preserving Medical Record Search (IoT)",
    subtitle: "Team Lead · Capstone · 3-engineer team",
    classification: "TLP:AMBER",
    status: "DELIVERED",
    stampColor: "signal",
    objective: "Enable searchable encrypted medical records over IoT diagnostics under strict HIPAA compliance — no plaintext leak at any node.",
    outcome: "Searchable scheme delivered with untraceable query patterns; passed compliance review for capstone evaluation.",
    steps: [
      "Modeled HIPAA-aligned threat surface for IoT diagnostics",
      "Designed searchable-encryption scheme with index-side blinding",
      "Built proof-of-concept service in Python + Flask",
      "Validated end-to-end with synthetic patient corpus",
    ],
    stack: ["HIPAA", "IoT", "Searchable Encryption", "Python", "Flask"],
    metrics: [
      { value: "HIPAA", label: "COMPLIANT" },
      { value: "0", label: "PLAINTEXT LEAKS" },
      { value: "T3", label: "TEAM SIZE" },
    ],
  },
  {
    title: "FBI Crime Analysis & Prediction (ML)",
    subtitle: "Mini-Project Team Lead",
    classification: "TLP:GREEN",
    status: "ARCHIVED",
    stampColor: "signal",
    objective: "Forecast crime hot-spots from open FBI datasets and surface actionable signals for proactive resource allocation.",
    outcome: "Models reached 90% accuracy on regional crime-rate prediction; presentation included a hot-spot map and intervention suggestions.",
    steps: [
      "Cleaned & feature-engineered FBI crime dataset",
      "Benchmarked logistic regression vs. random forest vs. GBM",
      "Cross-validated; final model at 90% accuracy",
      "Visualized hot-spots on a regional heatmap",
    ],
    stack: ["Python", "scikit-learn", "pandas", "Data Viz"],
    metrics: [
      { value: "90%", label: "ACCURACY" },
      { value: "5", label: "MODELS BENCHED" },
    ],
  },
];

const EXPERIENCE = [
  {
    role: "Co-Founder & Security Engineer",
    company: "Zhask — kaveo",
    location: "New York City, NY",
    from: "2025",
    to: "PRESENT",
    current: true,
    bullets: [
      "Co-founded Zhask and architected kaveo — an AI-native, self-hosted cloud security platform built on a hard rule: determinism finds the truth, AI has to show its work.",
      "Designed and shipped the detection engine — 96 deterministic detectors and 43 read-only AWS collectors covering exposure, identity, data, logging, network, and secrets across the IAM/reachability graph.",
      "Built the grounded-AI layer where every model claim is a (text, citation) pair validated against an immutable evidence ledger — uncited or misciting claims are dropped before they are ever stored, enforced in the data model rather than the prompt.",
      "Kept zero AI agents on the trust-critical detection path while supporting 7 interchangeable providers (Anthropic, Bedrock, OpenAI, Grok, self-hosted Ollama/vLLM, auto-router, offline) with zero-network mode by default.",
      "Closed the remediation loop end to end — prioritize by real blast radius, apply the fix through a scoped write role, re-scan to prove the finding no longer fires, then watch for drift and regression.",
      "Shipped a native MCP server giving customer AI agents read-only, cited access to findings — agent-native by design, self-hosted and zero-egress for regulated teams.",
      "Carried the product across 30+ surfaces with 300+ automated tests, backed by threat modeling against the OWASP LLM Top 10 and MITRE ATLAS.",
    ],
    tags: ["Co-Founder", "AWS", "Cloud Security", "AI Security", "Detection Engineering", "MCP", "Grounded AI", "Python", "Self-Hosted"],
  },
  {
    role: "Security Operations Center Analyst",
    company: "Security Validation | SecVal MSSP",
    location: "New Jersey, United States",
    from: "APR 2026",
    to: "PRESENT",
    current: true,
    bullets: [
      "Monitor and analyze security events across client environments using Stellar Cyber Open XDR and SIEM platforms to detect, triage, and respond to threats in real time.",
      "Leverage CrowdStrike Falcon for endpoint threat detection, investigation, and containment across client infrastructures.",
      "Support PCI DSS compliance monitoring for hospitality industry clients, ensuring cardholder data environments meet regulatory security standards.",
      "Perform alert investigation and incident response, correlating IOCs and TTPs against the MITRE ATT&CK framework.",
      "Conduct vulnerability assessments and communicate findings with actionable remediation guidance to clients.",
      "Tune detection rules and SIEM use cases to reduce false positives and improve signal fidelity.",
      "Collaborate cross-functionally to strengthen client security postures through continuous monitoring and threat intelligence integration.",
    ],
    tags: ["Stellar Cyber Open XDR", "SIEM", "CrowdStrike Falcon", "PCI DSS", "MITRE ATT&CK", "Incident Response", "Threat Intel"],
  },
  {
    role: "Cyber Security Analyst — Purple Team",
    company: "Cerner Healthcare Private Limited",
    location: "United States",
    from: "JUN 2025",
    to: "MAR 2026",
    current: false,
    bullets: [
      "Operated as a purple-team analyst across Cerner EHR environments — emulated adversary TTPs (red) and hardened detections (blue) in the same sprint, ensuring 100% alignment with HIPAA and healthcare security standards.",
      "Built centralized log aggregation across clinical apps, cloud platforms, and IAM — significantly increasing visibility and early threat identification.",
      "Improved MTTD by ~30% by developing automated detections tuned to healthcare-specific threats, ensuring EHR system integrity.",
      "Ran continuous vulnerability assessments using Tenable.io — prioritized remediation based on CVSS and clinical-risk impact to safeguard sensitive patient data.",
      "Tuned email security and DLP policies — mitigating phishing and BEC attacks while preventing unauthorized transmission of PHI across endpoints and cloud services.",
      "Partnered with cross-functional teams to enhance detection logic and response playbooks without disrupting critical patient-care workflows.",
    ],
    tags: ["Purple Team", "Splunk", "Sigma", "Tenable", "Proofpoint", "Forcepoint DLP", "CrowdStrike", "MITRE ATT&CK", "HIPAA", "EHR"],
  },
  {
    role: "Cyber Security Engineer",
    company: "Capgemini",
    location: "India",
    from: "JUN 2021",
    to: "JUL 2024",
    current: false,
    bullets: [
      "Integrated SIEM with financial transaction logs and ATM switches — built correlation rules that accelerated detection of fraud and insider misuse.",
      "Segmented SWIFT and payment networks by deploying NGFW and IDS/IPS; implemented RBAC and MFA to reduce the attack surface.",
      "Designed PCI-DSS and GDPR data-protection strategies — encryption, tokenization, and access controls — passing audits with zero major findings.",
      "Conducted pentests of online banking platforms using Burp Suite and OWASP methodology — identified and remediated critical SQLi and XSS vulnerabilities.",
      "Hardened payment gateways and APIs; partnered with risk teams to close audit gaps ahead of regulatory deadlines.",
      "Rolled out DLP across cloud and endpoints — automated compliance reporting and prevented unauthorized transfers of sensitive financial data.",
      "Improved forensic turnaround ~75% through expert use of EnCase and FTK — delivered litigation-ready reports for legal and compliance stakeholders.",
    ],
    tags: ["IBM QRadar", "Palo Alto NGFW", "Cisco ASA", "Burp Suite", "EnCase", "FTK", "PCI-DSS", "GDPR", "SWIFT"],
  },
];

// Single source of truth for badge verification — swap in the exact
// Credly profile/badge URLs once claimed.
const CREDLY_URL = "https://www.credly.com/users/rohith-donthula";

const CERTS = [
  { year: "2026", name: "CompTIA CNSP — Network Security Professional", issuer: "CompTIA Stackable · Security+ · CySA+ · PenTest+", status: "achieved", verify: CREDLY_URL, stackable: true },
  { year: "2026", name: "CompTIA CNVP — Network Vulnerability Assessment Professional", issuer: "CompTIA Stackable · Security+ · PenTest+", status: "achieved", verify: CREDLY_URL, stackable: true },
  { year: "2026", name: "CompTIA PenTest+", issuer: "CompTIA · PT0-003 · Penetration Testing", status: "achieved", verify: CREDLY_URL },
  { year: "2026", name: "MS Cybersecurity", issuer: "Yeshiva University · Aug 2024 – May 2026", status: "achieved" },
  { year: "2024", name: "CompTIA CSAP — Security Analytics Professional", issuer: "CompTIA Stackable · Security+ · CySA+", status: "achieved", verify: CREDLY_URL, stackable: true },
  { year: "2024", name: "CompTIA CySA+ (Security Analytics)", issuer: "CompTIA · CS0-003", status: "achieved", verify: CREDLY_URL },
  { year: "2024", name: "CompTIA Security+ CE", issuer: "CompTIA · SY0-701", status: "achieved", verify: CREDLY_URL },
  { year: "2024", name: "Cybersecurity Coursework", issuer: "IIIT Bangalore · Aug 2023 – Mar 2024", status: "achieved" },
  { year: "2023", name: "Google Cybersecurity Professional", issuer: "Coursera · Foundations + Manage Risks + Tools of the Trade", status: "achieved" },
];

Object.assign(window, { PROJECTS, EXPERIENCE, CERTS, CREDLY_URL });
